# Defines the plan from the planner agent in a structured manner
# Insead of giving the task as a whole string , each task is represented in a list format
# this is useful for the next agent


from pydantic import BaseModel,Field

class TaskList(BaseModel):

    """
    Tasks generated by the planner.
    """

    tasks: list[str] = Field(
        description="List of research tasks"
    )

